services:

  db:
    image: postgres:16
    container_name: contenedor_productos
    environment:
      POSTGRES_DB: Productos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123PP45
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: contenedor_app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
