name: CI/CD Azure Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: 1. Descargar c√≥digo
        uses: actions/checkout@v4

      - name: 2. Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 3. Compilar con Maven
        run: mvn clean package -DskipTests

      - name: 4. Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 5. Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/grupo4 .

      - name: 6. Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/grupo4

      - name: 7. Desplegar en Azure por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd micro_productos
            docker compose pull
            docker compose up -d
